### ISSUE TITLE
Jieba incorrect foramt  for vocab.txt

### ISSUE THREAD

**Issue by CrimsonNightZero** [chatopera/Synonyms#113]
Traceback (most recent call last):

  File "C:\Users\micke\anaconda3\lib\site-packages\jieba\posseg\__init__.py", line 105, in load_word_tag
    word, _, tag = line.split(" ")

ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\HereAPI\searchplace\searchplace-api\app\POSTag.py", line 9, in <module>
    from synonyms.jieba import posseg

  File "C:\Users\micke\anaconda3\lib\site-packages\synonyms\__init__.py", line 14, in <module>
    from .synonyms import *

  File "C:\Users\micke\anaconda3\lib\site-packages\synonyms\synonyms.py", line 87, in <module>
    _tokenizer.initialize(tokenizer_dict)

  File "C:\Users\micke\anaconda3\lib\site-packages\jieba\posseg\__init__.py", line 95, in initialize
    self.load_word_tag(self.tokenizer.get_dict_file())

  File "C:\Users\micke\anaconda3\lib\site-packages\jieba\posseg\__init__.py", line 109, in load_word_tag
    'invalid POS dictionary entry in %s at Line %s: %s' % (f_name, lineno, line))

ValueError: invalid POS dictionary entry in C:\Users\micke\anaconda3\lib\site-packages\synonyms\data\vocab.txt at Line 5008: 『 1 v 2 w

**Comment by Samurais** [comment]
Synonyms 版本是什么？

**Comment by Samurais** [comment]
刚刚发布了 3.15.0 版本解决此问题。感谢反馈！

**Comment by Samurais** [comment]
更新到最新版本

```
pip install -U synonyms
```

**Comment by CrimsonNightZero** [comment]
Version 3.13.0

5008只是其中一個，但還有其他的在vocab.txt文本裡。
