### ISSUE TITLE
pip install 后，pycharm运行提示找不到指定模块，但是juypter却能正常运行

### ISSUE THREAD

**Issue by nicolas-echo** [chatopera/Synonyms#117]
Traceback (most recent call last):
  File "E:/0_ImageNet/sample_ex/keyword_extraction/log/test1.py", line 10, in <module>
    import synonyms
  File "E:\Anaconda3\lib\site-packages\synonyms\__init__.py", line 13, in <module>
    from .word2vec import *
  File "E:\Anaconda3\lib\site-packages\synonyms\word2vec.py", line 36, in <module>
    from sklearn.neighbors import KDTree
  File "E:\Anaconda3\lib\site-packages\sklearn\__init__.py", line 76, in <module>
    from .base import clone
  File "E:\Anaconda3\lib\site-packages\sklearn\base.py", line 16, in <module>
    from .utils import _IS_32BIT
  File "E:\Anaconda3\lib\site-packages\sklearn\utils\__init__.py", line 20, in <module>
    from .validation import (as_float_array,
  File "E:\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 21, in <module>
    from .fixes import _object_dtype_isnan
  File "E:\Anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 18, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "E:\Anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .isolve import *
  File "E:\Anaconda3\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "E:\Anaconda3\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 10, in <module>
    from . import _iterative
ImportError: DLL load failed: 找不到指定的模块。

请问是缺少什么依赖的包没有安装吗？还是电脑环境有什么问题？

**Comment by hailiang-wang** [comment]
在 pycharm 中配置该项目的 Python interpreter

![image](https://user-images.githubusercontent.com/3538629/107175672-644d4400-6a08-11eb-9351-4945ef2eb6b2.png)


关于 PYTHONPATH 的基础不是我们帮忙的重点，基础只是请学习其他 Python 文档、书籍。
