### ISSUE TITLE
多卡训练无法使用

### ISSUE THREAD

**Issue by 480284856** [chatopera/Synonyms#133]
>> Synonyms on loading stopwords [/home/guxj/anaconda3/envs/NLP/lib/python3.8/site-packages/synonyms/data/stopwords.txt] ...
>> Synonyms on loading vectors [/home/guxj/anaconda3/envs/NLP/lib/python3.8/site-packages/synonyms/data/words.vector.gz] ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/guxj/code/T5/test2.0.py", line 4, in <module>
    import synonyms
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/site-packages/synonyms/synonyms.py", line 50, in <module>
    from .word2vec import KeyedVectors
**ImportError: attempted relative import with no known parent package**
Traceback (most recent call last):
  File "/home/guxj/code/T5/test2.0.py", line 349, in <module>
    main()
  File "/home/guxj/code/T5/test2.0.py", line 346, in main
    mp.spawn(train,nprocs=config.gpus,args=(config,))
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/guxj/anaconda3/envs/NLP/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1

为啥会这样？我在命令行上导入就可以，但运行多卡训练的脚本就会出错。

**Comment by hailiang-wang** [comment]
您反馈的这个问题，很重要！

问题发生原因，可参考 

https://blog.csdn.net/weixin_41699811/article/details/84965328

关于问题修复，欢迎提交 PR，我 merge 后会发布到 Synonyms 新版本。
